name        : libpwquality
version     : 1.3.0
release     : 5
source     :
    - https://launchpad.net/libpwquality/trunk/1.3.0/+download/libpwquality-1.3.0.tar.bz2 : 74d2ea90e103323c1f2d6a6cc9617cdae6877573eddb31aaf31a40f354cc2d2a
license     :
    - BSD-3-Clause
summary     : Library for password quality checking and generating random passwords.
builddeps   :
    - pkgconfig(python-2.7)
    - zlib-devel
    - pam-devel
    - cracklib-devel
description : |
    The libpwquality library purpose is to provide common functions for password quality checking and also scoring them based on their apparent randomness. The library also provides a function for generating random passwords with good pronounceability. The library supports reading and parsing of a configuration file.
setup      : |
    %configure --disable-static \
               --enable-python-bindings \
               --enable-pam \
               --with-securedir=/lib/security
build      : |
    %make
install    : |
    %make_install
